name: C++ Build and Test on Windows

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest  # 使用 Windows 最新版环境

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up MSVC
        run: |
          choco install visualstudio2019buildtools --version 16.11.7
          choco install cmake --version 3.21.0

      - name: Build C++ project
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .

      - name: Run tests
        run: .\your_test_executable.exe  # 用你的测试可执行文件替代此处
